#!/bin/sh
set -e
set -u

if [ -x /usr/bin/dpkg-architecture ]; then
    CMD=/usr/lib/$(dpkg-architecture --host-arch ${DPKG_MAINTSCRIPT_ARCH} --query DEB_HOST_MULTIARCH)/libgtk-3-0/gtk-query-immodules-3.0

    if [ -x ${CMD} ]; then
        case "$1" in
            configure)
                ${CMD} --update-cache
                ;;
        esac
    else
        echo "Cannot find gtk-query-immodules-3.0" > &2
    fi
else
    echo "Cannot find dpkg-architecture" > &2
fi

#DEBHELPER#

exit 0
